brand:
  name: "OmniTrade"
  logo: "/brand-assets/logo.png"
  logo_dark: "/brand-assets/logo_dark.png"
  logo_thumbnail: "/brand-assets/logo_thumbnail.png"
  website: "https://www.omnitrade.com.br"
  repository: "https://github.com/Tiagoeem/chatwoot_from_official"
  favicon: "/favicon.ico"

theme:
  colors:
    woot:
      25: "#faf5f0" # Fundo bege
      50: "#f5f0eb"
      75: "#f0ebe6"
      100: "#ebe6e1"
      200: "#e6e1dc"
      300: "#e1dcd7"
      400: "#dcd7d2"
      500: "#d7d2cd"
      600: "#d2cdc8"
      700: "#cdc8c3"
      800: "#c8c3be"
      900: "#7c726f" # Cinza mais escuro
