brand:
  name: "Sua Marca"
  logo: "/brand-assets/logo.svg"
  logo_dark: "/brand-assets/logo_dark.svg"
  logo_thumbnail: "/brand-assets/logo_thumbnail.svg"

theme:
  colors:
    woot:
      25: "#f0f7ff"
      50: "#e0efff"
      75: "#cce7ff"
      100: "#b8deff"
      200: "#a3d5ff"
      300: "#7bc4ff"
      400: "#52b3ff"
      500: "#29a1ff"
      600: "#008fff"
      700: "#007de6"
      800: "#006ccc"
      900: "#005ab3"
